# Generated by Django 5.2.4 on 2025-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('bank', 'Bank Account'), ('credit', 'Credit Card')], max_length=20),
        ),
    ]
